spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.18.128:8848
    sentinel:
      transport:
        dashboard: 192.168.18.128:8858
        port: 8719
  application:
    name: mall-seckill
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: 192.168.18.128
    port: 6380
  session:
    store-type: redis
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.18.128
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    #手动ack消息
    listener:
      simple:
        acknowledge-mode: manual
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 25000
#management:
#  endpoints:
#    web:
#      exposure:
#        include: /*