spring:
  cloud:
    gateway:
      routes:
#        - id: test_route
#          uri: https://www.baidu.com/
#          predicates:
#            - Query=url,baidu
#        - id: qq_route
#          uri: https://im.qq.com/index/
#          predicates:
#            - Query=url,qq
#前端项目/api
# http://localhost:88/api/captcha.jpg   ====>   http://localhost:8086/renren-fast/captcha.jpg
# http://localhost:88/api/product/category/list/tree    ====>   http://localhost:10000/product/category/list/tree
        - id: member_route
          uri: lb://mall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**,/hello
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: ware_route
          uri: lb://mall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: third_party_route
          uri: lb://mall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

        - id: mall_search_route
          uri: lb://mall-search
          predicates:
            - Host=search.mall.com

        - id: mall_auth_route
          uri: lb://mall-auth-server
          predicates:
            - Host=auth.mall.com

        - id: mall_cart_route
          uri: lb://mall-cart
          predicates:
            - Host=cart.mall.com
        - id: mall_order_route
          uri: lb://mall-order
          predicates:
            - Host=order.mall.com


        - id: mall_member_route
          uri: lb://mall-member
          predicates:
            - Host=member.mall.com


        - id: mall_host_route
          uri: lb://mall-product
          predicates:
            - Host=mall.com,item.mall.com

