spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com/
          predicates:
            - Query=url,baidu
        - id: qq_route
          uri: https://im.qq.com/index/
          predicates:
            - Query=url,qq