spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.18.128:8848
  thymeleaf:
    cache: false
  redis:
    host: 192.168.18.128
    port: 6380
  session:
    store-type: redis
    timeout: 30m
server:
  port: 20000