spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.18.128:3307/mall_oms?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.18.128:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: mall-order
  redis:
    host: 192.168.18.128
    port: 6380
  session:
    store-type: redis
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.18.128
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    #开启发送确认
#    publisher-confirm-type: simple
#    #开启发送端抵到队列确认
#    publisher-returns: true
#    #只要抵达队列，优先以异步模式回调returns_config
#    template:
#      mandatory: true
      #手动ack消息
#    listener:
#      simple:
#        acknowledge-mode: manual
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 13000